language: haskell
notifications:
  email:
    - cg.wowus.cg@gmail.com
  on_success: always
  on_failure: always

before_install:
    - cabal sandbox init
    - cabal install -j --only-dependencies --enable-tests --enable-benchmarks --with-hsc2hs=/usr/bin/with-hsc2hs

install:
    - cabal configure --enable-tests --enable-benchmarks -O2
    - cabal build

script:
    - cabal test -j --show-details=failures --test-options="-j 16 -a 100000 --color +RTS -N"
    - cabal bench || true
