language: haskell
notifications:
  email:
    - cg.wowus.cg@gmail.com
  on_success: always
  on_failure: always

before_install:
    - cabal sandbox init
    - cabal install --only-dependencies --enable-tests --enable-benchmarks --with-hsc2hs=/usr/bin/hsc2hs

install:
    - cabal configure --enable-tests --enable-benchmarks -O2
    - cabal build

script:
    - cabal test --show-details=always -j --test-options="-j 16 -a 100000 --color"
    - cabal bench || true
