language: haskell
notifications:
  email:
    - cg.wowus.cg@gmail.com
  on_success: always
  on_failure: always

before_install:
    - which ghc
    - which hsc2hs
    - which haddock
    - echo $PATH
    - cabal sandbox init
    - cabal install --only-dependencies --enable-tests --enable-benchmarks

install:
    - cabal configure --enable-tests --enable-benchmarks -O2
    - cabal build

script:
    - cabal test --show-details=always
    - cabal bench || true
